 - name: data_source
    description: This source contains all users data information.
    database: 'project_name'
    schema: 'dataset'
    tables:
      - name: user_logs
        description: '{{ doc("user_logs") }}'
        columns:
          - name: id
            type: STRING

          - name: ref
            type: STRING

          - name: action
            type: STRING

          - name: status
            type: STRING

          - name: state
            type: STRING
          
          - name: created
            type: TIMESTAMP
            
          - name: service
            type: STRING
          
          - name: request
            type: STRING
          
          - name: response
            type: STRING
  
          - name: month_created
            type: STRING